export default {
  SET_COUNTRY_STATIONS: "SET_COUNTRY_STATIONS",
  ADD_COUNTRY_STATIONS: "ADD_COUNTRY_STATIONS",
  COUNTRY_FETCH_STATUS: "COUNTRY_FETCH_STATUS",
  RESET_COUNTRY_REDUCER: "RESET_COUNTRY_REDUCER"
};
